title:             Yujin-Soft
email:
description:       https://Yujin-Soft.github.io
author:            Yujin-Soft
baseurl:           ""
url:               "https://Yujin-Soft.github.io"

# Social Profiles
twitter_username:
github_username:
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
